# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    allow:
      - dependency-type: "direct"  # Only packages listed in requirements.txt

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
