import gen10
from unipressed import UniprotkbClient

def get_uniprot_id():
    """
    This function retrieves the UniProt ID for a given protein sequence.
    It uses the gen10 library to perform the retrieval.
    """
    record = 0
    
    
    record = UniprotkbClient.fetch_one("Q96RW7")
    print(record)


# conversion tools
def fasta_reader():
    """
    This function reads a FASTA file and returns the sequences.
    """
    """
    Let's analyze each of your provided sequences to determine if any qualify as FASTA-formatted:

### **1. "TACCACGTGGACTGAGGACTCCTCATT"**  
- **Type**: Likely DNA sequence (T/A/C/G nucleotides).  
- **FASTA compliance**: **No** — missing the required `>` header line.  
- **How to fix**: Add a header (e.g., `>DNA_sequence1`).

---

### **2. "AUGGUGCACCUGACUCCUGAGGAGUAA"**  
- **Type**: Likely RNA sequence (A/U/C/G nucleotides).  
- **FASTA compliance**: **No** — missing `>` header.  
- **How to fix**: Add a header (e.g., `>RNA_sequence1`).

---

### **3. "Met Val His Leu Thr Pro Glu Glu"**  
- **Type**: Amino acid sequence (3-letter codes, space-separated).  
- **FASTA compliance**: **No** — FASTA uses **single-letter codes** (e.g., `MVHLTPEE`), and requires a header.  
- **How to fix**:  
  - Convert to single-letter codes.  
  - Add a header (e.g., `>Protein_sequence1`).

---

### **4. "MAGELVSFAVNKLWDLLSHEYTLFQGVEDQVAELKSDLNLLKSFLKDADAKKHTSALVRYCVEEIKDIVYDAEDVLETFVQKEKLGTTSGIRKHIKRLTCIVPDRREIALYIGHVSKRITRVIRDMQSFGVQQMIVDDYMHPLRNREREIRRTFPKDNESGFVALEENVKKLVGYFVEEDNYQVVSITGMGGLGKTTLARQVFNHDMVTKKFDKLAWVSVSQDFTLKNVWQNILGDLKPKEEETKEEEKKILEMTEYTLQRELYQLLEMSKSLIVLDDIWKKEDWEVIKPIFPPTKGWKLLLTSRNESIVAPTNTKYFNFKPECLKTDDSWKLFQRIAFPINDASEFEIDEEMEKLGEKMIEHCGGLPLAIKVLGGMLAEKYTSHDWRRLSENIGSHLVGGRTNFNDDNNNSCNYVLSLSFEELPSYLKHCFLYLAHFPEDYEIKVENLSYYWAAEEIFQPRHYDGEIIRDVGDVYIEELVRRNMVISERDVKTSRFETCHLHDMMREVCLLKAKEENFLQITSNPPSTANFQSTVTSRRLVYQYPTTLHVEKDINNPKLRSLVVVTLGSWNMAGSSFTRLELLRVLDLVQAKLKGGKLASCIGKLIHLRYLSLEYAEVTHIPYSLGNLKLLIYLNLHISLSSRSNFVPNVLMGMQELRYLALPSLIERKTKLELSNLVKLETLENFSTKNSSLEDLRGMVRLRTLTIELIEETSLETLAASIGGLKYLEKLEIDDLGSKMRTKEAGIVFDFVHLKRLRLELYMPRLSKEQHFPSHLTTLYLQHCRLEEDPMPILEKLLQLKELELGHKSFSGKKMVCSSCGFPQLQKLSISGLKEWEDWKVEESSMPLLLTLNIFDCRKLKQLPDEHLPSHLTAISLKKCGLEDPIPTLERLVHLKELSLSELCGRIMVCTGGGFPQLHKLDLSELDGLEEWIVEDGSMPRLHTLEIRRCLKLKKLPNGFPQLQNLHLTEVEEWEEGMIVKQGSMPLLHTLYIWHCPKLPGEQHFPSHLTTVFLLGMYVEEDPMRILEKLLHLKNVSLFQSFSGKRMVCSGGGFPQLQKLSIREIEWEEWIVEQGSMPLLHTLYIGVCPNLKELPDGLRFIYSLKNLIVSKRWKKRLSEGGEDYYKVQHIPSVEFDD"**  
- **Type**: Amino acid sequence (single-letter codes).  
- **FASTA compliance**: **No** — missing `>` header.  
- **How to fix**: Add a header (e.g., `>Large_protein_sequence`).

---

### **FASTA Conversion Examples**
- **DNA**:  
  ```
  >DNA_sequence1  
  TACCACGTGGACTGAGGACTCCTCATT
  ```
- **RNA**:  
  ```
  >RNA_sequence1  
  AUGGUGCACCUGACUCCUGAGGAGUAA
  ```
- **Protein (3-letter to single-letter conversion)**:  
  ```
  >Protein_sequence1  
  MVHLTPEE
  ```
- **Large protein**:  
  ```
  >Large_protein_sequence  
  MAGELVSFAVNKLWDLLSHEYTLFQGVEDQVAELKSDLNLLKSFLKDADAKKHTSALVRYCVEEIKDIVYDAEDVLETFVQKEKLGTTSGIRKHIKRLTCIVPDRREIALYIGHVSKRITRVIRDMQSFGVQQMIVDDYMHPLRNREREIRRTFPKDNESGFVALEENVKKLVGYFVEEDNYQVVSITGMGGLGKTTLARQVFNHDMVTKKFDKLAWVSVSQDFTLKNVWQNILGDLKPKEEETKEEEKKILEMTEYTLQRELYQLLEMSKSLIVLDDIWKKEDWEVIKPIFPPTKGWKLLLTSRNESIVAPTNTKYFNFKPECLKTDDSWKLFQRIAFPINDASEFEIDEEMEKLGEKMIEHCGGLPLAIKVLGGMLAEKYTSHDWRRLSENIGSHLVGGRTNFNDDNNNSCNYVLSLSFEELPSYLKHCFLYLAHFPEDYEIKVENLSYYWAAEEIFQPRHYDGEIIRDVGDVYIEELVRRNMVISERDVKTSRFETCHLHDMMREVCLLKAKEENFLQITSNPPSTANFQSTVTSRRLVYQYPTTLHVEKDINNPKLRSLVVVTLGSWNMAGSSFTRLELLRVLDLVQAKLKGGKLASCIGKLIHLRYLSLEYAEVTHIPYSLGNLKLLIYLNLHISLSSRSNFVPNVLMGMQELRYLALPSLIERKTKLELSNLVKLETLENFSTKNSSLEDLRGMVRLRTLTIELIEETSLETLAASIGGLKYLEKLEIDDLGSKMRTKEAGIVFDFVHLKRLRLELYMPRLSKEQHFPSHLTTLYLQHCRLEEDPMPILEKLLQLKELELGHKSFSGKKMVCSSCGFPQLQKLSISGLKEWEDWKVEESSMPLLLTLNIFDCRKLKQLPDEHLPSHLTAISLKKCGLEDPIPTLERLVHLKELSLSELCGRIMVCTGGGFPQLHKLDLSELDGLEEWIVEDGSMPRLHTLEIRRCLKLKKLPNGFPQLQNLHLTEVEEWEEGMIVKQGSMPLLHTLYIWHCPKLPGEQHFPSHLTTVFLLGMYVEEDPMRILEKLLHLKNVSLFQSFSGKRMVCSGGGFPQLQKLSIREIEWEEWIVEQGSMPLLHTLYIGVCPNLKELPDGLRFIYSLKNLIVSKRWKKRLSEGGEDYYKVQHIPSVEFDD
  ```

**Key Takeaway**: None of your examples are currently in FASTA format, but they can easily be converted by adding a header line starting with `>`. For amino acid sequences, ensure single-letter codes are used.

---
Answer from Perplexity: https://www.perplexity.ai/search/what-is-fasta-formatt-QP__WX96Q6eXbV2uMPYhyw?utm_source=copy_output"""

def fasta_writer():
    """
    This function writes sequences to a FASTA file.
    """