name: Python CI

on:
  push:
    branches: [main]  # or other branches you want to trigger the CI on
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t genten -f genten.dockerfile .

    # Step 4: Run tests in Docker container
    - name: Run tests with Docker
      run: |
        docker run genten pytest